config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true

  SPECIES = %w(dog act rabbit snake turtle)
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
   before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.create(pet_params)
    redirect_to @pet
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to @pet
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetFoundOrganization</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-6">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for(pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on, as: :date %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/pets/edit.html.erb
<%= render "form", pet: @pet %>

app/views/pets/index.html.erb
<h1>All the pets</h1>

<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to pet.name, pet_path(pet)  %></li>
  <% end %>
</ul>

<%= link_to 'Found a pet ?', new_pet_path, class: 'btn btn-primary' %>

app/views/pets/new.html.erb
<%= render "form", pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %> was found : </h1>
<h2><%= @pet.species %></h2>

<%= link_to pet_path(@pet),
            method: :delete,
            class: 'btn btn-danger btn-xs',
            data: { confirm: 'Are you sure ?'} do %>

  <i class="fas fa-trash-alt"></i>

<% end %>


<p>at <%= @pet.address %> - <%= time_ago_in_words(@pet.found_on) %> ago</p>


<%= link_to 'Back', pets_path, class: 'btn btn-secondary' %>
<%= link_to 'Edit', edit_pet_path(@pet), class: 'btn btn-warning' %>